#!/bin/bash

source ../config

cp config/config-prod.clj src/hwo2014bot/config.clj
cp config/log4j.properties.prod resources/log4j.properties

# lein uberjar

cp target/hwo2014bot-0.1.0-SNAPSHOT-standalone.jar bin/hwo2014bot-standalone.jar
